package main

import (
	"io/ioutil"

	"net/http"
	"net/http/httptest"
	"testing"
)

func TestPing(t *testing.T) {
	// Initialize a new httptest.ResponseRecorder. This is essentially an implementation of http.ResponseWriter which
	// records the response status code, headers and body instead of actually writing them to a HTTP connection

	rr := httptest.NewRecorder()
	r, err := http.NewRequest("GET", "/", nil)
	if err != nil {
		t.Fatal(err)
	}

	ping(rr, r)
	// Result() method on the http.ResponseRecorder to get the http.Response generated by the ping handler.
	rs := rr.Result()
	if rs.StatusCode != http.StatusOK {
		t.Errorf("want %d; got %d", http.StatusOK, rs.StatusCode)
	}
	defer rs.Body.Close()

	body, err := ioutil.ReadAll(rs.Body)
	if err != nil {
		t.Fatal(err)
	}

	if string(body) != "OK" {
		t.Errorf("want body to equal %q", "OK")
	}

	// we use the t.Fatal() function in a couple of places to handle situations where there is an unexpected
	// error in our test code. When called, t.Fatal() will mark the test as failed, log the error,
	// and then completely stop execution of any further tests
}
