name: Format
on:
  pull_request:

jobs:
  shfmt:
    runs-on: ubuntu-24.04

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Apply format
        run: go run mvdan.cc/sh/v3/cmd/shfmt@latest -i 2 -ci -bn -l -w .

      - name: Check diff
        run: git diff --exit-code
