package store

import "github.com/ahmad-khatib0/go/websockets/chat/internal/store/types"

// Unique ID generator
var uGen types.UidGenerator

// DecodeUid takes an XTEA encrypted Uid and decrypts it into an int64.
//
// This is needed for sql compatibility. Tte original int64 values
//
// are generated by snowflake which ensures that the top bit is unset.
func DecodeUid(uid types.Uid) int64 {
	if uid.IsZero() {
		return 0
	}
	return uGen.DecodeUid(uid)
}

// EncodeUid applies XTEA encryption to an int64 value. It's the inverse of DecodeUid.
func EncodeUid(id int64) types.Uid {
	if id == 0 {
		return types.ZeroUid
	}
	return uGen.EncodeInt64(id)
}
