// Code generated by mockery v2.52.1. DO NOT EDIT.

package mocks

import (
	db "github.com/ahmad-khatib0/go/test-driven-development/ch11_generics/db"
	mock "github.com/stretchr/testify/mock"
)

// MagazineOperationsService is an autogenerated mock type for the MagazineOperationsService type
type MagazineOperationsService struct {
	mock.Mock
}

// ListByUser provides a mock function with given fields: userID
func (_m *MagazineOperationsService) ListByUser(userID string) ([]db.Magazine, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []db.Magazine
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]db.Magazine, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(string) []db.Magazine); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.Magazine)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMagazineOperationsService creates a new instance of MagazineOperationsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMagazineOperationsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MagazineOperationsService {
	mock := &MagazineOperationsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
